// Generates src/tables/trig.rs with the trig/bitrev/scale tables that
// libvorbis's mdct_init would populate for n=2048.

use std::f64::consts::PI;

/// Format an f32 as a Rust literal that round-trips exactly.
/// We print enough decimal digits (9 significant digits is enough for f32).
fn fmt_f32(v: f32) -> String {
    if v.is_nan() {
        return "f32::NAN".to_string();
    }
    if v.is_infinite() {
        return if v > 0.0 {
            "f32::INFINITY".to_string()
        } else {
            "f32::NEG_INFINITY".to_string()
        };
    }
    // Use enough decimal digits that the value round-trips exactly.
    // 9 significant decimal digits are always sufficient for f32.
    let s = format!("{:.9e}", v);
    // Parse back to verify round-trip
    let reparsed: f32 = s.parse().unwrap();
    assert_eq!(
        v.to_bits(),
        reparsed.to_bits(),
        "round-trip failed for {:?}",
        v
    );
    // Append f32 suffix
    format!("{}_f32", s)
}

fn main() {
    let n: usize = 2048;
    let n2 = n / 2; // 1024
    let n4 = n / 4; // 512
    let n8 = n / 8; // 256

    // trig array: size n + n/4 = 2560
    // Layout mirrors mdct_init:
    //   T[0..n/2)      : i in 0..n/4  -> T[2i]    = cos(pi/n * 4i)
    //                                    T[2i+1]   = -sin(pi/n * 4i)
    //   T[n2..n2+n/2)  : i in 0..n/4  -> T[n2+2i]   = cos(pi/(2n) * (2i+1))
    //                                     T[n2+2i+1]  = sin(pi/(2n) * (2i+1))
    //   T[n..n+n/4)    : i in 0..n/8  -> T[n+2i]   = cos(pi/n * (4i+2)) * 0.5
    //                                     T[n+2i+1]  = -sin(pi/n * (4i+2)) * 0.5
    let trig_size = n + n4; // 2560
    let mut trig = vec![0f32; trig_size];

    for i in 0..n4 {
        trig[i * 2] = (PI / n as f64 * (4 * i) as f64).cos() as f32;
        trig[i * 2 + 1] = -(PI / n as f64 * (4 * i) as f64).sin() as f32;
        trig[n2 + i * 2] = (PI / (2 * n) as f64 * (2 * i + 1) as f64).cos() as f32;
        trig[n2 + i * 2 + 1] = (PI / (2 * n) as f64 * (2 * i + 1) as f64).sin() as f32;
    }
    for i in 0..n8 {
        trig[n + i * 2] = ((PI / n as f64 * (4 * i + 2) as f64).cos() * 0.5) as f32;
        trig[n + i * 2 + 1] = -((PI / n as f64 * (4 * i + 2) as f64).sin() * 0.5) as f32;
    }

    // bitrev array: size n/4 = 512
    // Mirrors mdct_init bit-reverse computation
    let log2n: u32 = (n as f64).log2().round() as u32; // 11
    let bitrev_size = n4; // 512
    let mut bitrev = vec![0u32; bitrev_size];
    {
        let mask: u32 = (1 << (log2n - 1)) - 1; // (1<<10)-1 = 1023
        let msb: u32 = 1 << (log2n - 2); // 1<<9 = 512
        for i in 0..n8 {
            let mut acc: u32 = 0;
            let mut j = 0u32;
            while (msb >> j) != 0 {
                if ((msb >> j) & i as u32) != 0 {
                    acc |= 1 << j;
                }
                j += 1;
            }
            bitrev[i * 2] = ((!acc) & mask) - 1;
            bitrev[i * 2 + 1] = acc;
        }
    }

    // scale = 4.0 / n
    let scale: f32 = 4.0f32 / n as f32;

    // Write the Rust source file
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by tools/gen-tables. Do not edit. Regenerate via 'just regen-trig-table'.\n");
    out.push_str("#![allow(clippy::excessive_precision)]\n\n");

    // TRIG_2048
    out.push_str(&format!("pub static TRIG_2048: [f32; {}] = [\n", trig_size));
    for (idx, &v) in trig.iter().enumerate() {
        if idx % 4 == 0 {
            out.push_str("    ");
        }
        out.push_str(&fmt_f32(v));
        if idx + 1 < trig_size {
            out.push(',');
            if idx % 4 == 3 {
                out.push('\n');
            } else {
                out.push(' ');
            }
        }
    }
    out.push_str("\n];\n\n");

    // BITREV_2048
    out.push_str(&format!(
        "pub static BITREV_2048: [u32; {}] = [\n",
        bitrev_size
    ));
    for (idx, &v) in bitrev.iter().enumerate() {
        if idx % 8 == 0 {
            out.push_str("    ");
        }
        out.push_str(&format!("{}", v));
        if idx + 1 < bitrev_size {
            out.push(',');
            if idx % 8 == 7 {
                out.push('\n');
            } else {
                out.push(' ');
            }
        }
    }
    out.push_str("\n];\n\n");

    // SCALE_2048
    out.push_str(&format!(
        "pub static SCALE_2048: f32 = {};\n",
        fmt_f32(scale)
    ));

    std::fs::write("src/tables/trig.rs", out).expect("failed to write src/tables/trig.rs");
    eprintln!(
        "Wrote src/tables/trig.rs ({} trig values, {} bitrev values, scale={})",
        trig_size, bitrev_size, scale
    );

    // Generate window table
    let win_n: usize = 2048;
    let mut window = vec![0f32; win_n];
    for i in 0..win_n {
        let s = (PI * (i as f64 + 0.5) / win_n as f64).sin();
        let w = (0.5 * PI * s * s).sin() as f32;
        window[i] = w;
    }

    // Verify COLA property: w[i]^2 + w[i + N/2]^2 = 1 for i in 0..N/2
    let mut max_err: f64 = 0.0;
    for i in 0..win_n / 2 {
        let a = window[i] as f64;
        let b = window[i + win_n / 2] as f64;
        let err = (a * a + b * b - 1.0).abs();
        if err > max_err {
            max_err = err;
        }
    }
    assert!(
        max_err < 1e-5,
        "window COLA property violated: max error = {max_err}"
    );
    eprintln!("Window COLA max error = {max_err:.2e}");

    let mut win_out = String::new();
    win_out.push_str(
        "// AUTO-GENERATED by tools/gen-tables. Do not edit. Regenerate via 'just regen-tables'.\n",
    );
    win_out.push_str("#![allow(clippy::excessive_precision)]\n\n");
    win_out.push_str(&format!(
        "pub static SIN_WINDOW_2048: [f32; {}] = [\n",
        win_n
    ));
    for (idx, &v) in window.iter().enumerate() {
        if idx % 4 == 0 {
            win_out.push_str("    ");
        }
        win_out.push_str(&fmt_f32(v));
        if idx + 1 < win_n {
            win_out.push(',');
            if idx % 4 == 3 {
                win_out.push('\n');
            } else {
                win_out.push(' ');
            }
        }
    }
    win_out.push_str("\n];\n");

    std::fs::write("src/tables/window.rs", win_out).expect("failed to write src/tables/window.rs");
    eprintln!("Wrote src/tables/window.rs ({win_n} values)");
}
